name: Call Audit Bot

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  dispatch-audit-request:
    # Only run for comments that start with /audit-bot
    if: >
      ${{
        startsWith(github.event.comment.body, '/audit-bot') &&
        (
          (github.event_name == 'issue_comment' &&
           github.event.issue.pull_request) ||
          github.event_name == 'pull_request_review_comment'
        )
      }}
    runs-on: ubuntu-latest

    # Minimal permissions for repository-dispatch
    permissions:
      actions: write
      contents: read

    steps:
      # Step 1: Generate a token scoped for the TARGET repository
      - name: Generate a token from the GitHub App
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          # Use the new kebab-case input names
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

          # --- THIS IS THE CRITICAL FIX ---
          # Specify the owner and repository where you want to use the token
          owner: 'Boolafish-Playground'
          repositories: 'test-target-workflow'

      # 2. DEBUG – print the first 10 characters of the token
      - name: DEBUG – show token prefix
        run: |
          echo "Generated token starts with: $(echo '${{ steps.generate-token.outputs.token }}' | cut -c1-10)"

      # - name: Send request to the audit workflow
      #   uses: peter-evans/repository-dispatch@v3
      #   with:
      #     # TEMPORARILY use the PAT instead of the App token for this test
      #     token: ${{ secrets.TEMP_PAT }}

      #     repository: Boolafish-Playground/test-target-workflow
      #     event-type: run-audit-bot
      #     client-payload: >-
      #       {
      #         "comment_body": ${{ toJSON(github.event.comment.body) }},
      #         "source_repo": "${{ github.repository }}",
      #         "pr_number": "${{ github.event.issue.number }}",
      #         "commenter": "${{ github.actor }}"
      #       }

      # 3. Trigger the downstream audit workflow
      - name: Send repository-dispatch event
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          repository: Boolafish-Playground/test-target-workflow
          event-type: run-audit-bot
          client-payload: |
            {
              "comment": ${{ toJSON(github.event.comment) }},
              "repository": "${{ github.repository }}",
              "issue": ${{ toJSON(github.event.issue) }},
              "pull_request": ${{ toJSON(github.event.pull_request) }}
            }
