name: Call Audit Bot

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  dispatch-audit-request:
    # Only run for comments that start with /audit-bot
    if: >
      ${{
        startsWith(github.event.comment.body, '/audit-bot') &&
        (
          (github.event_name == 'issue_comment' &&
           github.event.issue.pull_request) ||
          github.event_name == 'pull_request_review_comment'
        )
      }}
    runs-on: ubuntu-latest

    # Minimal permissions for repository-dispatch
    permissions:
      actions: write
      contents: read

    steps:
      # 1. Generate a token from the GitHub App
      - name: Generate GitHub App token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      # 2. DEBUG – print the first 10 characters of the token
      - name: DEBUG – show token prefix
        run: |
          echo "Generated token starts with: $(echo '${{ steps.generate-token.outputs.token }}' | cut -c1-10)"

      # 3. Trigger the downstream audit workflow
      - name: Send repository-dispatch event
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          repository: Boolafish-Playground/test-target-workflow
          event-type: run-audit-bot
          client-payload: |
            {
              "comment": ${{ toJSON(github.event.comment) }},
              "repository": "${{ github.repository }}",
              "issue": ${{ toJSON(github.event.issue) }},
              "pull_request": ${{ toJSON(github.event.pull_request) }}
            }
