name: PR Comment Debug

on:
  issue_comment: # Triggers for comments on an issue or a PR's main conversation
    types: [created]
  pull_request_review_comment: # Triggers for comments on specific lines of code in a PR review
    types: [created]

jobs:
  issue-comment-test:
    # This job runs if the event is an issue_comment AND
    # it's NOT associated with a pull request context directly in github.event.issue
    if: ${{ github.event_name == 'issue_comment' && !github.event.issue.pull_request }}
    runs-on: ubuntu-latest 
    steps:
      - name: Issue comment detected
        run: |
          echo "✅ Issue comment works!"
          echo "Comment: '${{ github.event.comment.body }}'"

  pr-comment-test:
    # This job runs if the event is an issue_comment AND
    # it IS associated with a pull request context in github.event.issue
    if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: PR comment detected
        run: |
          echo "✅ PR comment works!"
          echo "Comment: '${{ github.event.comment.body }}'"
          echo "PR number: ${{ github.event.issue.number }}"

  pr-review-comment-test:
    # This job runs if the event is a pull_request_review_comment
    # It uses github.event.pull_request to confirm it's a PR context
    if: ${{ github.event_name == 'pull_request_review_comment' }}
    runs-on: ubuntu-latest
    steps:
      - name: PR review comment detected
        run: |
          echo "✅ PR review comment works!"
          echo "Comment: '${{ github.event.comment.body }}'"