name: PR Comment Trigger

# Fire on EVERY new comment to a pull-request
on:
  issue_comment:
    types: [created]

jobs:
  react-to-pr-comment:
    # Make sure the comment is on a PR (not a plain issue)
    if: github.event.issue.pull_request != null

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 👉 add whatever steps you need below
      - name: Example action
        run: echo "Triggered by PR comment from ${{ github.event.comment.user.login }}"
