name: PR Comment Trigger

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  react-to-pr-comment:
    if: |
      github.event.issue.pull_request != null   # still ensure it’s a PR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Say who triggered me
        run: echo "Hello, ${{ github.event.comment.user.login }}!"
